name: Build and Save Artifacts
 
on:
  push:
    branches:
      - main
jobs:
  build-and-organize:
    runs-on: self-hosted
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 7.x
 
      - name: Build
        run: |
          cd D:\Githubtrainning\githubtrainning
          dotnet build --configuration Release
          dotnet publish -c Release -o out
      - name: Copy Artifacts
        run: |
          # Copy the artifacts to a designated directory

          #mkdir -p $HOME/artifacts
          if (-Not (Test-Path $HOME/artifacts)) {
              New-Item -ItemType Directory -Path $HOME/artifacts
          }
          cp -r C:\actions-runner\_work\D:\Githubtrainning\githubtrainning\out\* $HOME\artifacts\
          Remove the existing artifacts directory if it exists
          #Remove-Item -Path $HOME\artifacts -Recurse -Force -ErrorAction SilentlyContinue
          ## Create a new artifacts directory
          #New-Item -ItemType Directory -Path $HOME\artifacts
          ## Copy the artifacts to the new directory
          #Copy-Item -Path D:\Githubtrainning\githubtrainning\out\* -Destination $HOME\artifacts\ -Recursehas context menu
    environment:
      name: test-environment


