name: Build on Push
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: self-hosted
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with: 
            dotnet-version: 7.x
 
    - name: Build and Publish
      run: |
          cd D:\Githubtrainning\githubtrainning
          dotnet build --configuration Release
          dotnet publish -c Release -o out
