name: Display Repo Name and Username

on:
  push:
    branches:
      - main # Adjust this based on your default branch

jobs:
  display-repo-info:
    runs-on: ubuntu-latest

    steps:
      - name: Display Repo Info
        run: |
          repo_full_name="${{ github.repository }}"
          repo_owner="${repo_full_name%/*}"
          repo_name="${repo_full_name#*/}"

          echo "Repository Name: $repo_name"
          echo "Repository Owner: $repo_owner"
