name: Display Repo Name and Username

on: [push]

jobs:
  display-repo-info:
    runs-on: ubuntu-latest

    steps:
      - name: Display Repo Info
        run: |
          echo "Repository Name: ${{ github.repository }}"
          echo "Repository Owner: ${{ github.repository_owner }}"
